---
- name: Update System Package Cache
  ansible.builtin.apt:
    update_cache: true
  tags:
    - apt

- name: Upgrade System Packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  tags:
    - apt

- name: Installing additional packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt }}"
  register: result
  until: result is succeeded
  tags:
    - apt