---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Include prepare variables
      ansible.builtin.include_vars: "../../vars/ubuntu-22.04.yaml"
    - name: Perform basic configuration
      ansible.builtin.import_role:
        name: ansible-system-clean