---
- name: wrapper playbook for kitchen testing "prepare" with custom vars for testing
  hosts: all
  become: true
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  tasks:
    - name: include preparation tasks
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      loop:
        - prepare_tasks/install_dependencies.yml